mkdir flats
./generator data/surnames.txt data/names.txt data/patronymics.txt 1000 > flats/flats1000
./generator data/surnames.txt data/names.txt data/patronymics.txt 2000 > flats/flats2000
./generator data/surnames.txt data/names.txt data/patronymics.txt 3000 > flats/flats3000
./generator data/surnames.txt data/names.txt data/patronymics.txt 4000 > flats/flats4000
./generator data/surnames.txt data/names.txt data/patronymics.txt 5000 > flats/flats5000
./generator data/surnames.txt data/names.txt data/patronymics.txt 6000 > flats/flats6000
./generator data/surnames.txt data/names.txt data/patronymics.txt 7000 > flats/flats7000
./generator data/surnames.txt data/names.txt data/patronymics.txt 8000 > flats/flats8000
./generator data/surnames.txt data/names.txt data/patronymics.txt 9000 > flats/flats9000
./generator data/surnames.txt data/names.txt data/patronymics.txt 10000 > flats/flats10000
./generator data/surnames.txt data/names.txt data/patronymics.txt 11000 > flats/flats11000
./generator data/surnames.txt data/names.txt data/patronymics.txt 12000 > flats/flats12000
./generator data/surnames.txt data/names.txt data/patronymics.txt 13000 > flats/flats13000
./generator data/surnames.txt data/names.txt data/patronymics.txt 14000 > flats/flats14000
./generator data/surnames.txt data/names.txt data/patronymics.txt 15000 > flats/flats15000
./generator data/surnames.txt data/names.txt data/patronymics.txt 16000 > flats/flats16000
./generator data/surnames.txt data/names.txt data/patronymics.txt 17000 > flats/flats17000
./generator data/surnames.txt data/names.txt data/patronymics.txt 18000 > flats/flats18000
./generator data/surnames.txt data/names.txt data/patronymics.txt 19000 > flats/flats19000
./generator data/surnames.txt data/names.txt data/patronymics.txt 20000 > flats/flats20000

./generator data/surnames.txt data/names.txt data/patronymics.txt 100 > flats/flats100
./generator data/surnames.txt data/names.txt data/patronymics.txt 200 > flats/flats200
./generator data/surnames.txt data/names.txt data/patronymics.txt 300 > flats/flats300
./generator data/surnames.txt data/names.txt data/patronymics.txt 400 > flats/flats400
./generator data/surnames.txt data/names.txt data/patronymics.txt 500 > flats/flats500
./generator data/surnames.txt data/names.txt data/patronymics.txt 600 > flats/flats600
./generator data/surnames.txt data/names.txt data/patronymics.txt 700 > flats/flats700
./generator data/surnames.txt data/names.txt data/patronymics.txt 800 > flats/flats800
./generator data/surnames.txt data/names.txt data/patronymics.txt 900 > flats/flats900
./generator data/surnames.txt data/names.txt data/patronymics.txt 1000 > flats/flats1000
./generator data/surnames.txt data/names.txt data/patronymics.txt 1100 > flats/flats1100
./generator data/surnames.txt data/names.txt data/patronymics.txt 1200 > flats/flats1200
./generator data/surnames.txt data/names.txt data/patronymics.txt 1300 > flats/flats1300
./generator data/surnames.txt data/names.txt data/patronymics.txt 1400 > flats/flats1400
./generator data/surnames.txt data/names.txt data/patronymics.txt 1500 > flats/flats1500
./generator data/surnames.txt data/names.txt data/patronymics.txt 1600 > flats/flats1600
./generator data/surnames.txt data/names.txt data/patronymics.txt 1700 > flats/flats1700
./generator data/surnames.txt data/names.txt data/patronymics.txt 1800 > flats/flats1800
./generator data/surnames.txt data/names.txt data/patronymics.txt 1900 > flats/flats1900
./generator data/surnames.txt data/names.txt data/patronymics.txt 2000 > flats/flats2000
